# Generated by Django 5.0.6 on 2024-06-15 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_comment_developer_alter_task_comments_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
